var fsAT=await import("node:fs/promises");
await fsAT.mkdir("/home/user/workspace/antigen-tail-qa",{recursive:true});
var checksAT=[];
function checkAT(ok,name){if(!ok)throw Error(name);checksAT.push(name);}
async function readyAT(){await atPage.locator("#output").waitFor({state:"visible"});}
async function runAT(){await atPage.locator("#run").click();await readyAT();}
await atPage.reload({waitUntil:"networkidle"});await readyAT();
checkAT((await atPage.locator("#means").innerText())==="50,000 / 50,000","Default equal means");
checkAT((await atPage.locator("#tails").innerText())==="0.00% / 20.00%","Default tails");
checkAT((await atPage.locator("#stats").innerText()).includes("20.05%"),"Hypothetical response values");
for(var [key,expected]of [["crossing","100.00% / 20.00%"],["identical","10.00% / 10.00%"],["zero","0.00% / 25.00%"],["tail","0.00% / 20.00%"]]){
 await atPage.locator("#preset").selectOption(key);await atPage.locator("#load").click();await readyAT();
 checkAT((await atPage.locator("#tails").innerText())===expected,`Preset ${key}`);
}
await atPage.locator("#threshold").fill("60000");
checkAT(await atPage.locator("#output").isHidden(),"Stale results hidden on edit");
await runAT();checkAT((await atPage.locator("#tailGap").innerText()).includes("-80.00"),"Edited threshold reversal");
await atPage.locator("#threshold").fill("");await atPage.locator("#run").click();
checkAT((await atPage.locator("#status").innerText()).includes("required"),"Blank threshold blocked");
await atPage.locator("#reset").click();await readyAT();
await atPage.locator("#data-panel summary").click();
await atPage.locator("#unitsB").selectOption("mesf");await atPage.locator("#run").click();
checkAT((await atPage.locator("#status").innerText()).includes("scales differ"),"Unit mismatch blocked");
await atPage.locator("#unitsB").selectOption("abc");await atPage.locator("#run").click();
checkAT((await atPage.locator("#status").innerText()).includes("shared measurement"),"Unit change clears comparability");
await atPage.locator("#compatible").check();await atPage.locator("#resolved").uncheck();await atPage.locator("#run").click();
checkAT((await atPage.locator("#status").innerText()).includes("quantitatively resolved"),"Unresolved tail blocked");
await atPage.locator("#resolved").check();
await atPage.locator("#dataA").fill("<100");await atPage.locator("#run").click();
await atPage.waitForFunction(()=>document.getElementById("status").textContent.includes("Censored"));
checkAT(await atPage.locator("#output").isHidden(),"Censored input rejected");
await atPage.locator("#dataA").fill("-1");await atPage.locator("#run").click();
await atPage.waitForFunction(()=>document.getElementById("status").textContent.includes("nonnegative"));
checkAT(await atPage.locator("#output").isHidden(),"Negative values rejected without clipping");
await atPage.locator("#reset").click();await readyAT();
await atPage.locator("#origin").selectOption("empirical");
checkAT(!(await atPage.locator("#compatible").isChecked())&&!(await atPage.locator("#resolved").isChecked()),"Empirical mode clears synthetic assertions");
await atPage.locator("#compatible").check();await atPage.locator("#resolved").check();await atPage.locator("#run").click();
checkAT((await atPage.locator("#status").innerText()).includes("require calibration"),"Empirical notes required");
await atPage.locator("#notes").fill("QA only: simulated observations; shared calibration, complete gates, resolved tail; one biological preparation per population.");
await atPage.locator("#dataA").fill("100\n200\n300");await atPage.locator("#dataB").fill("100,1\n200,1\n300,1");
await runAT();checkAT((await atPage.locator("#headline").innerText()).includes("Same supplied"),"Event values and exact counts agree");
await atPage.locator("#reset").click();await readyAT();
await atPage.getByText("Descriptive comparison margins",{exact:true}).click();
await atPage.locator("#tailMargin").fill("90");await runAT();
checkAT((await atPage.locator("#bandConclusion").innerText()).includes("Within"),"Descriptive margin changes result");
await atPage.locator("#lower").fill("2000");await atPage.locator("#upper").fill("4000");await runAT();
checkAT((await atPage.locator("#status").innerText()).includes("outside the sweep"),"Out-of-sweep point warning");
checkAT((await atPage.locator("#bandGap").innerText())==="20.00 pp","Interval-specific exact distance");
await atPage.locator("#reset").click();await readyAT();
var jsonDownloadAT=atPage.waitForEvent("download");await atPage.locator("#exportJSON").click();var jsonFileAT=await jsonDownloadAT;
await jsonFileAT.saveAs("/home/user/workspace/antigen-tail-qa/report.json");
var reportAT=JSON.parse(await fsAT.readFile("/home/user/workspace/antigen-tail-qa/report.json","utf8"));
checkAT(reportAT.comparison.dGlobal===.8&&reportAT.metadata.origin==="synthetic"&&reportAT.limitations.length===4,"JSON numerical provenance and limitations");
var csvDownloadAT=atPage.waitForEvent("download");await atPage.locator("#exportCSV").click();var csvFileAT=await csvDownloadAT;
await csvFileAT.saveAs("/home/user/workspace/antigen-tail-qa/sweep.csv");
var csvTextAT=await fsAT.readFile("/home/user/workspace/antigen-tail-qa/sweep.csv","utf8");
checkAT(csvTextAT.split("\n").length===102&&csvTextAT.includes("hypothetical_unresponsive"),"CSV row count and conditional labels");
checkAT((await atPage.request.get("http://127.0.0.1:8082/model.md")).ok(),"Math document available");
checkAT((await atPage.request.get("http://127.0.0.1:8082/model.js")).ok(),"Code download available");
await atPage.locator("#theme").click();
checkAT(await atPage.locator("html").getAttribute("data-theme")==="light","Light toggle");
await atPage.screenshot({path:"/home/user/workspace/antigen-tail-qa/light.png"});
await atPage.locator("#theme").click();
checkAT(await atPage.locator("html").getAttribute("data-theme")==="dark","Dark toggle return");
checkAT(!await atPage.evaluate(()=>document.documentElement.scrollWidth>innerWidth),"Desktop no page overflow");
checkAT(atErrors.length===0,"No browser errors");
await fsAT.writeFile("/home/user/workspace/antigen-tail-qa/functional-results.json",JSON.stringify(checksAT,null,2));
console.log(JSON.stringify({passed:checksAT.length,checks:checksAT,errors:atErrors},null,2));
