import {readFileSync,writeFileSync} from "node:fs";
const root=new URL("../web/",import.meta.url);
const core=readFileSync(new URL("model.js",root),"utf8").replace(/^export /gm,"");
const worker=readFileSync(new URL("worker.js",root),"utf8").replace(/^import .*;\n/m,"");
// A self-contained classic Blob worker supports opaque-origin preview iframes.
// Generated from the same core exercised by the Node tests; never edit by hand.
writeFileSync(new URL("worker-source.js",root),"// Generated by scripts/build-worker.mjs; do not edit.\nexport const WORKER_SOURCE="+JSON.stringify(core+"\n"+worker)+";\n");
const joint=readFileSync(new URL("joint-model.js",root),"utf8").replace(/^import .*;\n/gm,"").replace(/^export /gm,"");
const jointWorker=readFileSync(new URL("joint-worker.js",root),"utf8").replace(/^import .*;\n/gm,"");
writeFileSync(new URL("joint-worker-source.js",root),"// Generated by scripts/build-worker.mjs; do not edit.\nexport const JOINT_WORKER_SOURCE="+JSON.stringify(core+"\n"+joint+"\n"+jointWorker)+";\n");
const delivery=readFileSync(new URL("delivery-model.js",root),"utf8").replace(/^export /gm,"");
const deliveryWorker=readFileSync(new URL("delivery-worker.js",root),"utf8").replace(/^import .*;\n/gm,"");
writeFileSync(new URL("delivery-worker-source.js",root),"// Generated by scripts/build-worker.mjs; do not edit.\nexport const DELIVERY_WORKER_SOURCE="+JSON.stringify(delivery+"\n"+deliveryWorker)+";\n");
const pd=readFileSync(new URL("delivery-pd-model.js",root),"utf8").replace(/^import .*;\n/gm,"").replace(/^export /gm,"");
const pdAudit=readFileSync(new URL("delivery-pd-audit.js",root),"utf8").replace(/^export /gm,"");
const pdWorker=readFileSync(new URL("delivery-pd-worker.js",root),"utf8").replace(/^import .*;\n/gm,"");
writeFileSync(new URL("delivery-pd-worker-source.js",root),"// Generated by scripts/build-worker.mjs; do not edit.\nexport const PD_WORKER_SOURCE="+JSON.stringify(delivery+"\n"+pdAudit+"\n"+pd+"\n"+pdWorker)+";\n");
