import {readFileSync,writeFileSync} from "node:fs";
const root=new URL("../web/",import.meta.url);
const core=readFileSync(new URL("model.js",root),"utf8").replace(/^export /gm,"");
const worker=readFileSync(new URL("worker.js",root),"utf8").replace(/^import .*;\n/m,"");
// A self-contained classic Blob worker supports opaque-origin preview iframes.
// Generated from the same core exercised by the Node tests; never edit by hand.
writeFileSync(new URL("worker-source.js",root),"// Generated by scripts/build-worker.mjs; do not edit.\nexport const WORKER_SOURCE="+JSON.stringify(core+"\n"+worker)+";\n");
